an-anime-team/an-anime-game-launcher

- src/ts/Game.ts
- src/ts/Voice.ts
- src/ts/core/Download.ts
- src/ts/launcher/State.ts
- src/ts/types/GameData.d.ts
* Check the size and MD5 checksum of the pre-downloaded packages
* If the package is not fully downloaded, resume the download
* If the downloaded package is too big or the MD5 checksum mismatches, remove it and re-download.
> Support resuming pre-downloaded packages

- src/ts/Voice.ts
- src/ts/launcher/states/InstallVoice.ts
The launcher failed to find the predownloaded voice pack due to checking for wrong version.
> Fix applying voice predownloads and 3.4.0 voice update

- README.md
Still points to the wiki at the old gtk repository. Also made the sentence a little more concise.
> Update link to the documentation

- Cargo.lock
- Cargo.toml
- src/ui/first_run/main.rs
- src/ui/main.rs
- src/ui/preferences/main.rs
Instead of using a command, use the wrapper.
Crate is https://lib.rs/crates/open, usable on other OSes as well.
> Use open library for xdg

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- assets/locales/de/errors.ftl
- assets/locales/de/sandbox.ftl
- assets/locales/en/errors.ftl
- assets/locales/en/sandbox.ftl
- assets/locales/es/errors.ftl
- assets/locales/es/general.ftl
- assets/locales/es/sandbox.ftl
- assets/locales/fr/errors.ftl
- assets/locales/fr/sandbox.ftl
- assets/locales/ru/errors.ftl
- assets/locales/ru/sandbox.ftl
- assets/locales/tr/errors.ftl
- assets/locales/tr/sandbox.ftl
- assets/locales/zh-cn/errors.ftl
- assets/locales/zh-cn/sandbox.ftl
- fluentscan.py
- src/ui/about.rs
- src/ui/preferences/environment.rs
- src/ui/preferences/main.rs
- src/ui/preferences/sandbox.rs
Small update with further sandbox settings development and some important fixes on SDK's side
- - [x] Update Russian
- - [ ] Update German
- - [ ] Update Spanish
- - [ ] Update French
- - [ ] Update Turkish
- - [ ] Update Chinese
- - [x] Test bwrap args and symlinks
- - [ ] Test sandboxed game launching (doesn't work now?)
> Release 3.5.2

- assets/locales/common.ftl
- assets/locales/ja/components.ftl
- assets/locales/ja/enhancements.ftl
- assets/locales/ja/environment.ftl
- assets/locales/ja/errors.ftl
- assets/locales/ja/first_run.ftl
- assets/locales/ja/game.ftl
- assets/locales/ja/gamescope.ftl
- assets/locales/ja/general.ftl
- assets/locales/ja/main.ftl
- assets/locales/ja/sandbox.ftl
- src/i18n.rs
> Japanese translation

- fluentscan.py
- code is now better organized and maintainable 
- made the 2nd parameter (en,ru,es,etc) not required when the command "unused" or "missing" is being used
- output is now sent to a pager
> refactor: rewrite some parts of fluentscanner.py

- assets/locales/sv/enhancements.ftl
- assets/locales/sv/environment.ftl
- assets/locales/sv/game.ftl
- assets/locales/sv/main.ftl
Just general language improvements
> Improving swedish translations

- assets/locales/common.ftl
- assets/locales/vi/components.ftl
- assets/locales/vi/enhancements.ftl
- assets/locales/vi/environment.ftl
- assets/locales/vi/errors.ftl
- assets/locales/vi/first_run.ftl
- assets/locales/vi/game.ftl
- assets/locales/vi/gamescope.ftl
- assets/locales/vi/general.ftl
- assets/locales/vi/main.ftl
- assets/locales/vi/sandbox.ftl
- src/i18n.rs
Vietnamese is a language support by miHoYo in SEA server
.
.
.
.
.
I don't play/like GI or HSR, but I hope the translation have in Honkers Launchers.
> Add Vietnamese

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- assets/locales/common.ftl
- assets/locales/vi/components.ftl
- assets/locales/vi/enhancements.ftl
- assets/locales/vi/environment.ftl
- assets/locales/vi/errors.ftl
- assets/locales/vi/first_run.ftl
- assets/locales/vi/game.ftl
- assets/locales/vi/gamescope.ftl
- assets/locales/vi/general.ftl
- assets/locales/vi/main.ftl
- assets/locales/vi/sandbox.ftl
- assets/locales/zh-cn/components.ftl
- assets/locales/zh-cn/enhancements.ftl
- assets/locales/zh-cn/errors.ftl
- assets/locales/zh-cn/general.ftl
- assets/locales/zh-cn/main.ftl
- src/i18n.rs
- src/main.rs
- src/ui/about.rs
- src/ui/first_run/dependencies.rs
- src/ui/first_run/welcome.rs
Since devs have removed full game files zip archive we now have to use segmented ones. This release will utilize them.
- - [x] Test segmented zip files downloading
> Release 3.9.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- assets/locales/common.ftl
- assets/locales/nl/components.ftl
- assets/locales/nl/enhancements.ftl
- assets/locales/nl/environment.ftl
- assets/locales/nl/errors.ftl
- assets/locales/nl/first_run.ftl
- assets/locales/nl/game.ftl
- assets/locales/nl/gamescope.ftl
- assets/locales/nl/general.ftl
- assets/locales/nl/main.ftl
- assets/locales/nl/sandbox.ftl
- src/i18n.rs
Some translations might sound a bit unnatural since I don't talk
about these kinds of things in Dutch often, so any changes are welcome!
> Add Dutch translation 

- assets/locales/tr/components.ftl
- assets/locales/tr/enhancements.ftl
- assets/locales/tr/environment.ftl
- assets/locales/tr/errors.ftl
- assets/locales/tr/first_run.ftl
- assets/locales/tr/game.ftl
- assets/locales/tr/general.ftl
- fluentscan.py
_also i accidentally tampered with fluentscan.py script while working, and reverted back to the original script._
> updated Turkish

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- assets/locales/de/main.ftl
- assets/locales/en/main.ftl
- assets/locales/es/main.ftl
- assets/locales/fr/main.ftl
- assets/locales/hu/main.ftl
- assets/locales/id/main.ftl
- assets/locales/it/main.ftl
- assets/locales/ja/main.ftl
- assets/locales/ko/main.ftl
- assets/locales/nl/main.ftl
- assets/locales/pl/main.ftl
- assets/locales/pt/main.ftl
- assets/locales/ru/main.ftl
- assets/locales/sv/main.ftl
- assets/locales/tr/components.ftl
- assets/locales/tr/enhancements.ftl
- assets/locales/tr/environment.ftl
- assets/locales/tr/errors.ftl
- assets/locales/tr/first_run.ftl
- assets/locales/tr/game.ftl
- assets/locales/tr/general.ftl
- assets/locales/tr/main.ftl
- assets/locales/vi/main.ftl
- assets/locales/zh-cn/main.ftl
- src/ui/about.rs
- src/ui/components/progress_bar.rs
- src/ui/main/mod.rs
This update brings new FPS Unlocker version, as well as new voiceovers sizes for better version prediction
> Release 3.9.3

- src/ui/main/mod.rs
> fix: update wish url

- assets/locales/common.ftl
- assets/locales/cs/components.ftl
- assets/locales/cs/enhancements.ftl
- assets/locales/cs/environment.ftl
- assets/locales/cs/errors.ftl
- assets/locales/cs/first_run.ftl
- assets/locales/cs/game.ftl
- assets/locales/cs/gamescope.ftl
- assets/locales/cs/general.ftl
- assets/locales/cs/main.ftl
- assets/locales/cs/sandbox.ftl
- src/i18n.rs
Hello, this pull request adds (hopefully) complete czech localization.
> add czech localization

- src/main.rs
Instead of just try to run UI with invalid argument to fail, it will just fail with better error messages.
Fixes #327
---
Do I need to use `next` branch for dev changes?
> Show some helpful error when --run-game cannot work

- .github/workflows/check_source_code.yml
- .github/workflows/compile_release_build.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- assets/locales/common.ftl
- assets/locales/cs/components.ftl
- assets/locales/cs/enhancements.ftl
- assets/locales/cs/environment.ftl
- assets/locales/cs/errors.ftl
- assets/locales/cs/first_run.ftl
- assets/locales/cs/game.ftl
- assets/locales/cs/gamescope.ftl
- assets/locales/cs/general.ftl
- assets/locales/cs/main.ftl
- assets/locales/cs/sandbox.ftl
- src/i18n.rs
- src/main.rs
- src/ui/about.rs
- src/ui/first_run/default_paths.rs
- src/ui/preferences/enhancements/mod.rs
- src/ui/preferences/general/mod.rs
> Release 3.9.6

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/background.rs
- src/ui/about.rs
Hotfix. Devs have changed their API format once again.
> Release 3.10.1

- src/i18n.rs
- src/main.rs
This change works pretty well and also gets rid of some unsafe :)
> refactor: remove unsafe in i18n

- README.md
Moved the PPA to my own name per https://github.com/an-anime-team/an-anime-game-launcher/pull/396.
Please let me know if I need to do anything else.
> Add third-party DEB package link

- assets/locales/de/enhancements.ftl
- assets/locales/de/gamescope.ftl
I copied the positions of the dots from the `en` locale but you might want to make them more consistent.
> Update `de` locales

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/ui/components/progress_bar.rs
support for sophon downloader/patcher in the launcher
> feat: New download method

- .github/workflows/check_source_code.yml
- .github/workflows/compile_release_build.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- flake.lock
- flake.nix
- src/main.rs
- src/ui/about.rs
- src/ui/components/progress_bar.rs
In the current update developers have changed the game installation method. I announced that I won't work on its support, but fortunately community managed to research it and @JohnTheCoolingFan has implemented all the related logic in the core library. Thank him for letting this project survive this change!
> Release 1.14.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/ui/about.rs
- src/ui/components/progress_bar.rs
A set of improvements and fixes to the sophon integration.
> Release 1.14.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- flake.lock
- src/main.rs
- src/ui/about.rs
- src/ui/components/progress_bar.rs
- src/ui/main/mod.rs
- src/ui/main/repair_game.rs
Fix game repairing and pre-downloading using the new game downloads format.
> Release 3.14.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- flake.lock
- flake.nix
- src/ui/about.rs
- src/ui/main/repair_game.rs
- src/ui/preferences/general/mod.rs
- src/ui/preferences/main.rs
Cumulative update with some sophon code refactoring.
> Release 3.14.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/ui/about.rs
- src/ui/main/mod.rs
> Release 3.15.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/i18n.rs
- src/ui/about.rs
- src/ui/main/repair_game.rs
Fix to locale lookup and fix for "faield to find game diff" (#552)
> Release 3.15.6

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/ui/first_run/download_components.rs
- src/ui/preferences/enhancements/game.rs
- src/ui/preferences/general/components.rs
Proton support was not working properly as of now anyway, and there is no real reason to try keeping it alive for longer.
> Remove Proton support

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/ui/about.rs
- src/ui/first_run/download_components.rs
- src/ui/preferences/enhancements/game.rs
- src/ui/preferences/general/components.rs
Removed support for launching with proton via the launcher
> Release 3.16.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- assets/locales/en/main.ftl
- src/ui/about.rs
- src/ui/main/install_dxvk.rs
- src/ui/main/mod.rs
Relevant pull requests:
- DXVK installatio ncheck by @NelloKudo: #564, https://github.com/an-anime-team/anime-launcher-sdk/pull/27
- Fix for FPS unlocker not working with some runners by @JohnTheCoolingFan: https://github.com/an-anime-team/anime-launcher-sdk/pull/28
> Release 3.17.0
